nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

enableGlobalCache: true

nmMode: "hardlinks-global"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
